### ISSUE TITLE
No response on hello world example

### ISSUE THREAD

**Issue by phantomxe** [squeaky-pl/japronto#117]
``
Accepting connections on http://0.0.0.0:8080
Exception in callback UVTransport._call_connection_made
handle: <Handle UVTransport._call_connection_made>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 52, in uvloop.loop.Handle._run
  File "uvloop/handles/tcp.pyx", line 149, in uvloop.loop.TCPTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 156, in uvloop.loop.UVBaseTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 153, in uvloop.loop.UVBaseTransport._call_connection_made
SystemError: NULL result without error in PyObject_Call
``
I got this error in hello world example. I'm running on ubuntu 16.04.

**Comment by squeaky-pl** [comment]
Duplicate: https://github.com/squeaky-pl/japronto/issues/115
