### ISSUE TITLE
can not install by pip

### ISSUE THREAD

**Issue by hotea** [squeaky-pl/japronto#167]
ERROR: Could not find a version that satisfies the requirement japronto (from versions: none)
ERROR: No matching distribution found for japronto

**Comment by testshiling** [comment]
Neither can I.The same error.

**Comment by testshiling** [comment]
You could install the source code by git.Then go into the installation diractory.Run "python setup.py build“ and "python setup.py install".

**Comment by eirnym** [comment]
Currently you need to run `python setup.py install` manually and there's no binary distributions.

I think the `japonito` was never released in `pip` just because author is not sure that it's stable enough. Probably, author could say better for himself. I'd wish it would be some day even daily releases. From that it's much easier to distinguish how and when to update.

**Comment by rubby33** [comment]
@eirnym @testshiling ,

I use python setup.py install,but it still fail.
my os version is: macOS 10.14.2 .
Thanks

`(py3.7) IT-C02YPCXVLVCF:japronto jonny$ python setup.py install
{'japronto.response.cresponse': ['src/japronto/response/cresponse.c', 'src/japronto/capsule.c'], 'japronto.protocol.creaper': ['src/japronto/protocol/creaper.c', 'src/japronto/capsule.c'], 'japronto.protocol.cprotocol': ['src/japronto/protocol/cprotocol.c', 'src/japronto/capsule.c', 'src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/parser/cparser.c', 'src/japronto/cpu_features.c', 'src/japronto/pipeline/cpipeline.c'], 'japronto.request.crequest': ['src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c'], 'japronto.router.cmatcher': ['src/japronto/router/cmatcher.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c']}
running install
running bdist_egg
running egg_info
creating src/japronto.egg-info
writing src/japronto.egg-info/PKG-INFO
writing dependency_links to src/japronto.egg-info/dependency_links.txt
writing entry points to src/japronto.egg-info/entry_points.txt
writing requirements to src/japronto.egg-info/requires.txt
writing top-level names to src/japronto.egg-info/top_level.txt
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/runner.py -> build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/reloader.py -> build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/__main__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto
creating build/lib.macosx-10.7-x86_64-3.7/japronto/pipeline
copying src/japronto/pipeline/cpipeline_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/pipeline
copying src/japronto/pipeline/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/pipeline
copying src/japronto/pipeline/test_pipeline.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/pipeline
creating build/lib.macosx-10.7-x86_64-3.7/japronto/app
copying src/japronto/app/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/app
creating build/lib.macosx-10.7-x86_64-3.7/japronto/response
copying src/japronto/response/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/response
copying src/japronto/response/cresponse_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/response
copying src/japronto/response/py.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/response
creating build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/creaper_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/tracing.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/handler.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/null.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/cprotocol_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/generator_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
creating build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/parser/test_parser.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/parser/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/parser/cffiparser.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/parser/build_libpicohttpparser.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/parser/cparser_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
creating build/lib.macosx-10.7-x86_64-3.7/japronto/request
copying src/japronto/request/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/request
copying src/japronto/request/crequest_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/request
creating build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/test_matcher.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/test_analyzer.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/matcher.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/route.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/analyzer.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/cmatcher_ext.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/test_route.py -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/capsule.c -> build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/cpu_features.c -> build/lib.macosx-10.7-x86_64-3.7/japronto
copying src/japronto/pipeline/cpipeline.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/pipeline
copying src/japronto/response/cresponse.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/response
copying src/japronto/protocol/cprotocol.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/protocol/creaper.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/protocol
copying src/japronto/parser/cparser.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/parser
copying src/japronto/request/crequest.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/request
copying src/japronto/router/cmatcher.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
copying src/japronto/router/match_dict.c -> build/lib.macosx-10.7-x86_64-3.7/japronto/router
running build_ext
building 'src/picohttpparser/ssepicohttpparser.o'
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -msse4.2 -c -o src/picohttpparser/ssepicohttpparser.o src/picohttpparser/picohttpparser.c
src/picohttpparser/picohttpparser.c:27:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_ext': build.custom_build_ext}
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jonny/git/japronto/build.py", line 265, in build_extensions
    options={'unix': ['-msse4.2']})
  File "/Users/jonny/git/japronto/build.py", line 281, in compile_c
    subprocess.check_call(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-msse4.2', '-c', '-o', 'src/picohttpparser/ssepicohttpparser.o', 'src/picohttpparser/picohttpparser.c']' returned non-zero exit status 1.
(py3.7) IT-C02YPCXVLVCF:japronto jonny$ python setup.py build
{'japronto.response.cresponse': ['src/japronto/response/cresponse.c', 'src/japronto/capsule.c'], 'japronto.protocol.creaper': ['src/japronto/protocol/creaper.c', 'src/japronto/capsule.c'], 'japronto.protocol.cprotocol': ['src/japronto/protocol/cprotocol.c', 'src/japronto/capsule.c', 'src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/parser/cparser.c', 'src/japronto/cpu_features.c', 'src/japronto/pipeline/cpipeline.c'], 'japronto.request.crequest': ['src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c'], 'japronto.router.cmatcher': ['src/japronto/router/cmatcher.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c']}
running build
running build_py
running egg_info
writing src/japronto.egg-info/PKG-INFO
writing dependency_links to src/japronto.egg-info/dependency_links.txt
writing entry points to src/japronto.egg-info/entry_points.txt
writing requirements to src/japronto.egg-info/requires.txt
writing top-level names to src/japronto.egg-info/top_level.txt
reading manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
running build_ext
building 'src/picohttpparser/ssepicohttpparser.o'
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -msse4.2 -c -o src/picohttpparser/ssepicohttpparser.o src/picohttpparser/picohttpparser.c
src/picohttpparser/picohttpparser.c:27:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_ext': build.custom_build_ext}
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jonny/git/japronto/build.py", line 265, in build_extensions
    options={'unix': ['-msse4.2']})
  File "/Users/jonny/git/japronto/build.py", line 281, in compile_c
    subprocess.check_call(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-msse4.2', '-c', '-o', 'src/picohttpparser/ssepicohttpparser.o', 'src/picohttpparser/picohttpparser.c']' returned non-zero exit status 1.
(py3.7) IT-C02YPCXVLVCF:japronto jonny$ ls
CHANGELOG.md		__pycache__		cases			integration_tests	tutorial
LICENSE.txt		benchmarks		conftest.py		misc
MANIFEST.in		build			do_wrk.py		setup.py
README.md		build.py		examples		src
(py3.7) IT-C02YPCXVLVCF:japronto jonny$ python setup.py install
{'japronto.response.cresponse': ['src/japronto/response/cresponse.c', 'src/japronto/capsule.c'], 'japronto.protocol.creaper': ['src/japronto/protocol/creaper.c', 'src/japronto/capsule.c'], 'japronto.protocol.cprotocol': ['src/japronto/protocol/cprotocol.c', 'src/japronto/capsule.c', 'src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/parser/cparser.c', 'src/japronto/cpu_features.c', 'src/japronto/pipeline/cpipeline.c'], 'japronto.request.crequest': ['src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c'], 'japronto.router.cmatcher': ['src/japronto/router/cmatcher.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c']}
running install
running bdist_egg
running egg_info
writing src/japronto.egg-info/PKG-INFO
writing dependency_links to src/japronto.egg-info/dependency_links.txt
writing entry points to src/japronto.egg-info/entry_points.txt
writing requirements to src/japronto.egg-info/requires.txt
writing top-level names to src/japronto.egg-info/top_level.txt
reading manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
building 'src/picohttpparser/ssepicohttpparser.o'
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -msse4.2 -c -o src/picohttpparser/ssepicohttpparser.o src/picohttpparser/picohttpparser.c
src/picohttpparser/picohttpparser.c:27:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_ext': build.custom_build_ext}
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jonny/git/japronto/build.py", line 265, in build_extensions
    options={'unix': ['-msse4.2']})
  File "/Users/jonny/git/japronto/build.py", line 281, in compile_c
    subprocess.check_call(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-msse4.2', '-c', '-o', 'src/picohttpparser/ssepicohttpparser.o', 'src/picohttpparser/picohttpparser.c']' returned non-zero exit status 1.
(py3.7) IT-C02YPCXVLVCF:japronto jonny$ python3 setup.py install
{'japronto.response.cresponse': ['src/japronto/response/cresponse.c', 'src/japronto/capsule.c'], 'japronto.protocol.creaper': ['src/japronto/protocol/creaper.c', 'src/japronto/capsule.c'], 'japronto.protocol.cprotocol': ['src/japronto/protocol/cprotocol.c', 'src/japronto/capsule.c', 'src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/parser/cparser.c', 'src/japronto/cpu_features.c', 'src/japronto/pipeline/cpipeline.c'], 'japronto.request.crequest': ['src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c'], 'japronto.router.cmatcher': ['src/japronto/router/cmatcher.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c']}
running install
running bdist_egg
running egg_info
writing src/japronto.egg-info/PKG-INFO
writing dependency_links to src/japronto.egg-info/dependency_links.txt
writing entry points to src/japronto.egg-info/entry_points.txt
writing requirements to src/japronto.egg-info/requires.txt
writing top-level names to src/japronto.egg-info/top_level.txt
reading manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
building 'src/picohttpparser/ssepicohttpparser.o'
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -msse4.2 -c -o src/picohttpparser/ssepicohttpparser.o src/picohttpparser/picohttpparser.c
src/picohttpparser/picohttpparser.c:27:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_ext': build.custom_build_ext}
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jonny/git/japronto/build.py", line 265, in build_extensions
    options={'unix': ['-msse4.2']})
  File "/Users/jonny/git/japronto/build.py", line 281, in compile_c
    subprocess.check_call(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-msse4.2', '-c', '-o', 'src/picohttpparser/ssepicohttpparser.o', 'src/picohttpparser/picohttpparser.c']' returned non-zero exit status 1.
(py3.7) IT-C02YPCXVLVCF:japronto jonny$ python setup.py install
{'japronto.response.cresponse': ['src/japronto/response/cresponse.c', 'src/japronto/capsule.c'], 'japronto.protocol.creaper': ['src/japronto/protocol/creaper.c', 'src/japronto/capsule.c'], 'japronto.protocol.cprotocol': ['src/japronto/protocol/cprotocol.c', 'src/japronto/capsule.c', 'src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/parser/cparser.c', 'src/japronto/cpu_features.c', 'src/japronto/pipeline/cpipeline.c'], 'japronto.request.crequest': ['src/japronto/request/crequest.c', 'src/japronto/response/cresponse.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c'], 'japronto.router.cmatcher': ['src/japronto/router/cmatcher.c', 'src/japronto/router/match_dict.c', 'src/japronto/capsule.c']}
running install
running bdist_egg
running egg_info
writing src/japronto.egg-info/PKG-INFO
writing dependency_links to src/japronto.egg-info/dependency_links.txt
writing entry points to src/japronto.egg-info/entry_points.txt
writing requirements to src/japronto.egg-info/requires.txt
writing top-level names to src/japronto.egg-info/top_level.txt
reading manifest file 'src/japronto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/japronto.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
building 'src/picohttpparser/ssepicohttpparser.o'
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -I/opt/anaconda3/envs/py3.7/include -arch x86_64 -msse4.2 -c -o src/picohttpparser/ssepicohttpparser.o src/picohttpparser/picohttpparser.c
src/picohttpparser/picohttpparser.c:27:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    cmdclass={'build_ext': build.custom_build_ext}
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/jonny/git/japronto/build.py", line 265, in build_extensions
    options={'unix': ['-msse4.2']})
  File "/Users/jonny/git/japronto/build.py", line 281, in compile_c
    subprocess.check_call(cmd)
  File "/opt/anaconda3/envs/py3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-I/opt/anaconda3/envs/py3.7/include', '-arch', 'x86_64', '-msse4.2', '-c', '-o', 'src/picohttpparser/ssepicohttpparser.o', 'src/picohttpparser/picohttpparser.c']' returned non-zero exit status 1.`
